openapi: 3.0.3
info:
  title: Kiosk API
  description: |-
    Kiosk API OpenAPI 3.0 specification.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  termsOfService: http://trejosoft.com.do/terms/
  contact:
    email: administrator@trejosoft.com.do
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://kiosk-api.trejosoft.com.do/api/v1/
tags:
  - name: statuses
    description: Status related to each type of object 
  - name: priorities
    description: Turn or queue priorities 
  - name: categories
    description: Categories are higher-level classification or grouping of customers or visitors based on the nature or purpose of their visit.
  - name: services
    description: Services are specific assistance or task that a customer or visitor needs to be addressed at a service point (e.g., a service counter or desk).
  - name: customers
    description: Customers are visitors served by service agent or service counter 
  - name: appointments
    description: Appointments are pre-scheduled or pre-arranged time when a customer is expected to visit a service location to receive a specific service. 
  - name: serviceturns
    description: Service turns are customer's or visitor's time to be served by a service agent or at a service counter on a specific.
  - name: queues
    description: Queues are sequence of customers or individuals waiting for a service or assistance.
paths:
  # -----------------------------------------------------------
  # Statuses Endpoints
  # -----------------------------------------------------------
  /statuses:
    get:
      tags:
        - statuses
      summary: Get list of statuses
      description: Get list of statuses
      operationId: getStatusAll
      security:
        - KioskOAuth2:
            - read_statuses
            - admin_statuses
    post:
      tags:
        - statuses
      summary: Add a new status
      description: Add a new status
      operationId: addStatus
      security:
        - KioskOAuth2:
            - write_statuses
            - admin_statuses
  /statuses/{statusId}:
    get:
      tags:
        - statuses
      summary: Get info of an existing status
      description: Get info of an existing status by Id
      operationId: getStatus
      security:
        - KioskOAuth2:
            - read_statuses
            - admin_statuses
    put:
      tags:
        - statuses
      summary: Update an existing status
      description: Update an existing status by Id
      operationId: updateStatus
      security:
        - KioskOAuth2:
            - write_statuses
            - admin_statuses
    patch:
      tags:
        - statuses
      summary: Update partially an existing status
      description: Update partially an existing status by Id
      operationId: updatePartialStatus
      security:
        - KioskOAuth2:
            - write_statuses
            - admin_statuses
    delete:
      tags:
        - statuses
      summary: Delete an existing status
      description: Delete an existing status by Id
      operationId: deleteStatus
      security:
        - KioskOAuth2:
            - write_statuses
            - admin_statuses
            
  # -----------------------------------------------------------
  # Priorities Endpoints
  # -----------------------------------------------------------
  /priorities:
    get:
      tags:
        - priorities
      summary: Get list of priorities
      description: Get list of priorities
      operationId: getPriorityAll
      security:
        - KioskOAuth2:
            - read_priorities
            - admin_priorities
    post:
      tags:
        - priorities
      summary: Add a new priority
      description: Add a new priority
      operationId: addPriority
      security:
        - KioskOAuth2:
            - write_priorities
            - admin_priorities
            
  /priorities/{priorityId}:
    get:
      tags:
        - priorities
      summary: Get info of an existing priority
      description: Get info of an existing priority by Id
      operationId: getPriority
      security:
        - KioskOAuth2:
            - read_priorities
            - admin_priorities
    put:
      tags:
        - priorities
      summary: Update an existing priority
      description: Update an existing priority by Id
      operationId: updatePriority
      security:
        - KioskOAuth2:
            - write_priorities
            - admin_priorities
    patch:
      tags:
        - priorities
      summary: Update partially an existing priority
      description: Update partially an existing priority by Id
      operationId: updatePartialPriority
      security:
        - KioskOAuth2:
            - write_priorities
            - admin_priorities
    delete:
      tags:
        - priorities
      summary: Delete an existing priority
      description: Delete an existing priority by Id
      operationId: deletePriority
      security:
        - KioskOAuth2:
            - write_priorities
            - admin_priorities
            
  # -----------------------------------------------------------
  # Categories Endpoints
  # -----------------------------------------------------------
  /categories:
    get:
      tags:
        - categories
      summary: Get list of categories
      description: Get list of categories
      operationId: getCategoryAll
      security:
        - KioskOAuth2:
            - read_categories
            - admin_categories
    post:
      tags:
        - categories
      summary: Add a new category
      description: Add a new category
      operationId: addCategory
      security:
        - KioskOAuth2:
            - write_categories
            - admin_categories
  /categories/{categoryId}:
    get:
      tags:
        - categories
      summary: Get info of an existing category
      description: Get info of an existing category by Id
      operationId: getCategory
      security:
        - KioskOAuth2:
            - read_categories
            - admin_categories
    put:
      tags:
        - categories
      summary: Update an existing category
      description: Update an existing category by Id
      operationId: updateCategory
      security:
        - KioskOAuth2:
            - write_categories
            - admin_categories
    patch:
      tags:
        - categories
      summary: Update partially an existing category
      description: Update partially an existing category by Id
      operationId: updatePartialCategory
      security:
        - KioskOAuth2:
            - write_categories
            - admin_categories
    delete:
      tags:
        - categories
      summary: Delete an existing category
      description: Delete an existing category by Id
      operationId: deleteCategory
      security:
        - KioskOAuth2:
            - write_categories
            - admin_categories
  /categories/{categoryId}/services:
    get:
      tags:
        - categories
      summary: Get list of services of an existing category
      description: Get list of services of an existing category by Id
      operationId: getCategoryServices
      security:
        - KioskOAuth2:
            - read_categories
            - admin_categories
            
  # -----------------------------------------------------------
  # Services Endpoints
  # -----------------------------------------------------------
  /services:
    get:
      tags:
        - services
      summary: Get list of services
      description: Get list of services
      operationId: getServiceAll
      security:
        - KioskOAuth2:
            - read_services
            - admin_services
    post:
      tags:
        - services
      summary: Add a new service
      description: Add a new service
      operationId: addService
      security:
        - KioskOAuth2:
            - write_services
            - admin_services
            
  /services/{serviceId}:
    get:
      tags:
        - services
      summary: Get info of an existing service
      description: Get info of an existing service by Id
      operationId: getService
      security:
        - KioskOAuth2:
            - read_services
            - admin_services
    put:
      tags:
        - services
      summary: Update an existing service
      description: Update an existing service by Id
      operationId: updateService
      security:
        - KioskOAuth2:
            - write_services
            - admin_services
    patch:
      tags:
        - services
      summary: Update partially an existing service
      description: Update partially an existing service by Id
      operationId: updatePartialService
      security:
        - KioskOAuth2:
            - write_services
            - admin_services
    delete:
      tags:
        - services
      summary: Delete an existing service
      description: Delete an existing service by Id
      operationId: deleteService
      security:
        - KioskOAuth2:
            - write_services
            - admin_services
            
  /services/{serviceId}/serviceturns:
    get:
      tags:
        - services
      summary: Get list of turns of an existing service
      description: Get info of an existing service by Id
      operationId: getServiceTurns
      security:
        - KioskOAuth2:
            - read_services
            - admin_services

  # -----------------------------------------------------------
  # Customers Endpoints
  # -----------------------------------------------------------
  /customers:
    get:
      tags:
        - customers
      summary: Get list of customers
      description: Get list of customers
      operationId: getCustomerAll
      security:
        - KioskOAuth2:
            - read_customers
            - admin_customers
    post:
      tags:
        - customers
      summary: Add a new customer
      description: Add a new customer
      operationId: addCustomer
      security:
        - KioskOAuth2:
            - write_customers
            - admin_customers
            
  /customers/{customerId}:
    get:
      tags:
        - customers
      summary: Get info of an existing customer
      description: Get info of an existing customer by Id
      operationId: getCustomer
      security:
        - KioskOAuth2:
            - read_customers
            - admin_customers
    put:
      tags:
        - customers
      summary: Update an existing customer
      description: Update an existing customer by Id
      operationId: updateCustomer
      security:
        - KioskOAuth2:
            - write_customers
            - admin_customers
    patch:
      tags:
        - customers
      summary: Update partially an existing customer
      description: Update partially an existing customer by Id
      operationId: updatePartialCustomer
      security:
        - KioskOAuth2:
            - write_customers
            - admin_customers
    delete:
      tags:
        - customers
      summary: Delete an existing customer
      description: Delete an existing customer by Id
      operationId: deletecustomer
      security:
        - KioskOAuth2:
            - write_customers
            - admin_customers
            
  /customers/{customerId}/appointments:
    get:
      tags:
        - customers
      summary: Get list of appointments of an existing customer
      description: Get list of appointments of an existing customer by customer Id
      operationId: getCustomerAppointments
      security:
        - KioskOAuth2:
            - read_customers
            - admin_customers

  /customers/{customerId}/serviceturns:
    get:
      tags:
        - customers
      summary: Get list of turns of an existing customer
      description: Get list of turns an existing customer by customer Id
      operationId: getCustomerServiceTurns
      security:
        - KioskOAuth2:
            - read_customers
            - admin_customers
            - read_serviceturns
            - admin_serviceturns

  # -----------------------------------------------------------
  # Appointments Endpoints
  # -----------------------------------------------------------
  /appointments:
    get:
      tags:
        - appointments
      summary: Get list of appointments
      description: Get list of appointments
      operationId: getAppointmentAll
      security:
        - KioskOAuth2:
            - read_appointments
            - admin_appointments
    post:
      tags:
        - appointments
      summary: Add a new Appointment
      description: Add a new Appointment
      operationId: addAppointment
      security:
        - KioskOAuth2:
            - write_appointments
            - admin_appointments
            
  /appointments/{appointmentId}:
    get:
      tags:
        - appointments
      summary: Get info of an existing appointment
      description: Get info of an existing appointment by Id
      operationId: getAppointment
      security:
        - KioskOAuth2:
            - read_appointments
            - admin_appointments
    put:
      tags:
        - appointments
      summary: Update an existing appointment
      description: Update an existing appointment by Id
      operationId: updateAppointment
      security:
        - KioskOAuth2:
            - write_appointments
            - admin_appointments
    patch:
      tags:
        - appointments
      summary: Update partially an existing appointment
      description: Update partially an existing appointment by Id
      operationId: updatePartialAppointment
      security:
        - KioskOAuth2:
            - write_appointments
            - admin_appointments
    delete:
      tags:
        - appointments
      summary: Delete an existing appointment
      description: Delete an existing appointment by Id
      operationId: deleteAppointment
      security:
        - KioskOAuth2:
            - write_appointments
            - admin_appointments

  # -----------------------------------------------------------
  # ServiceTurns Endpoints
  # -----------------------------------------------------------
  /serviceturns:
    get:
      tags:
        - serviceturns
      summary: Get list of service turns
      description: Get list of service turns
      operationId: getServiceTurnAll
      security:
        - KioskOAuth2:
            - read_serviceturns
            - admin_serviceturns
    post:
      tags:
        - serviceturns
      summary: Add a new service turn
      description: Add a new service turn
      operationId: addServiceTurn
      security:
        - KioskOAuth2:
            - write_serviceturns
            - admin_serviceturns
            
  /serviceturns/{serviceTurnId}:
    get:
      tags:
        - serviceturns
      summary: Get info of an existing service turn
      description: Get info of an existing service turn by Id
      operationId: getServiceTurn
      security:
        - KioskOAuth2:
            - read_serviceturns
            - admin_serviceturns
    put:
      tags:
        - serviceturns
      summary: Update an existing service turn
      description: Update an existing service turn by Id
      operationId: updateServiceTurn
      security:
        - KioskOAuth2:
            - write_serviceturns
            - admin_serviceturns
    patch:
      tags:
        - serviceturns
      summary: Update partially an existing service turn
      description: Update partially an existing service turn by Id
      operationId: updatePartialServiceTurn
      security:
        - KioskOAuth2:
            - write_serviceturns
            - admin_serviceturns
    delete:
      tags:
        - serviceturns
      summary: Delete an existing service turn
      description: Delete an existing service turn by Id
      operationId: deleteServiceTurn
      security:
        - KioskOAuth2:
            - write_serviceturns
            - admin_serviceturns

# ====================================================================
# Components
# ====================================================================
components:
  
  # Parameters
  # ==========
  # Schemas
  # =======
  # Request Bodies
  # ==============
  # Responses
  # ==============
  securitySchemes:
    KioskOAuth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://trejosoft.com.do/kiosk-api/v1/oauth/authorize
          scopes:
            read_statuses: Read status information
            write_statuses: Create, modify and delete status information
            admin_statuses: Administrate status information
            read_priorities: Read priority information
            write_priorities: Create, modify and delete priority information
            admin_priorities: Administrate priority information
            read_categories: Read category information
            write_categories: Create, modify and delete category information
            admin_categories: Administrate category information
            read_services: Read service information
            write_services: Create, modify and delete service information
            admin_services: Administrate service information
            read_customers: Read customer information
            write_customers: Create, modify and delete customer information
            admin_customers: Administrate customer information
            read_appointments: Read customers' appointments information
            write_appointments: Create, modify and delete customers' appointments information
            admin_appointments: Administrate customers' appointments information
            read_serviceturns: Read services turns information
            write_serviceturns: Create, modify and delete services turns information
            admin_serviceturns: Administrate services turns information
            read_queues: Read queue information
            write_queues: Create, modify and delete queue information
            admin_queues: Administrate queue information
    ApiKeyAuth:
      type: apiKey
      name: api_key
      in: header